name: Update tzdata
on:
  schedule:
    # Check once every 12 hours
    - cron:  '0 */12 * * *'
jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade tox
      - name: Get updated data
        run: |
          tox -e update
      - name: Check for new data
        run: |
          # Early exit if no updates are found
          if ! git diff-index -- quiet HEAD; then
            exit 0
          else
            # The tzdata.zi file starts with a version comment
            VERSION=$(cat src/tzdata/zoneinfo/tzdata.zi | \
                      head -n 1 | \
                      sed 's/#version //' |
                      awk '{$1=$1};1')
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update tzdata to ${{ env.VERSION }}
          title: Update tzdata to ${{ env.VERSION }}
          body: |
            This is an automated update to the time zone database.
            
            The changelog should be available at:
            <https://github.com/eggert/tz/blob/${{ env.VERSION }}/NEWS>
          branch: tz-update-${{ env.VERSION }}
